"""ref-user-profile

Revision ID: 2f72634de6c6
Revises: ce1947539303
Create Date: 2025-02-27 21:01:38.534454

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f72634de6c6'
down_revision: Union[str, None] = 'ce1947539303'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('UserProfile', 'username',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('UserProfile', 'password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('UserProfile', 'password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('UserProfile', 'username',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
