"""category_delete_type

Revision ID: b8558464e5ba
Revises: 53abdf9762cb
Create Date: 2024-12-08 22:44:51.809035

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8558464e5ba'
down_revision: Union[str, None] = '53abdf9762cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Categories', 'type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Categories', sa.Column('type', sa.VARCHAR(), nullable=False))
    # ### end Alembic commands ###
